version: "3.1"

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      database__client: sqlite3
      database__connection__filename: "content/data/ghost-test.db"
      url: http://localhost:8080
    volumes:
      - ./.docker-data/minima:/var/lib/ghost/content
